.TH visualnovel-common 1 "October 24, 2008" "Debian-visualnovel"
.SH NAME
.B visualnovel-common
.B visualnovel-<metapackage_name>
\- package information and auto-apt helper

.SH SYNOPSIS
.B visualnovel-common
.B visualnovel-<metapackage_name>

.SH DESCRIPTION
Print just a simple information page about every visualnovel-* package
of the Debian visualnovel Blend.  Each metapackage has a 
.I /usr/bin/visualnovel-<metapackage_name>
file which should print some usefull informations and could be serve
as auto-apt helper.

.SH AUTHOR
Andreas Tille <tille@debian.org>.
