.TH KANATEST 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
kanatest \- a beginner's drill game to learn Japanese kana characters
.SH SYNOPSIS
.B kanatest
.SH "DESCRIPTION"
.B kanatest
is a simple hiragana and katakana drill game. It checks your knowledge of
Japanese kana characters.
.PP
There are three drill modes: hiragana mode (hiragana charset only), katakana
mode (katakana charset only) and mixed mode (both charsets). The tester shows
random kana characters and waits until you enter the romaji equivalent in an
entry field. At the end, statistics are provided.
.PP
kanatest uses GTK 2.

.SH OPTIONS
There are no options for kanatest.

.SH AUTHOR
This manual page was written by Sam Hocevar <sho@debian.org> for the Debian
GNU/Linux distribution because the original program did not have a manual
page.
